name: Build and Update

on:
  pull_request_target:
    branches:
      - main
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: translate
    env:
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      RAW_TERMS_URL: https://gist.github.com/JounQin/8f323563651794ec371588c0d5c3bf1b/raw/71f1eae4f5744e4a78b95244c1d1fa9305d8c471/terms.yaml
      AZURE_OPENAI_MODEL: gpt-4o-mini
    permissions:
      contents: write  # 必需：允许 push 到 PR
      pull-requests: write 

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}  # 确保 checkout 到 PR 的分支
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 可根据项目调整

      - name: Setup Yarn
        run: |
          corepack enable
          yarn set version stable

      - name: Upgrade dependencies
        run: |
          yarn up @alauda/doom
          yarn up -R '**'

      - name: Install dependencies (immutable)
        run: yarn --immutable

      - name: generate id
        run: ./add_id.sh docs/en/solutions

      - name: translate
        run: yarn translate -s en -t zh -g "*"

      - name: Build
        run: yarn build

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "ci: update file from GitHub Action" || echo "Nothing to commit"
          git push origin HEAD:${{ github.head_ref }}
